// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementAPI.Data;

#nullable disable

namespace UserManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250202181636_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserManagementAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "$2a$11$mJSma0fivtpFTG2kGiPEkuVAvDTj3Xbo5OZS0IXxaf0eLWrOHcL72",
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "$2a$11$lhwGjaKMqG49iLUu3w62/.zmNFbY9aZA0X6T8Bd4kPyqlrw2X7B2y",
                            UserName = "jane.smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Password = "$2a$11$pCyoAPqkHfukxaHdjAtpT.lYQvjKXOM.ycM.VVZycZk7vVc5YXJXO",
                            UserName = "alice.johnson"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Brown",
                            Password = "$2a$11$a.yaZBkbkGzqo.42YYIkke/KROhx1Co2aZ54kJO3zfnxrPozSi8/S",
                            UserName = "bob.brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
